### ISSUE TITLE
client.js is using deprecated methods which may soon be removed

### ISSUE THREAD

**Issue by cmebarrow** [kaazing/webrtc#19]
We are using the following methods on RTCPeerConnection, but they are deprecated according to https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection:
- onaddstream 
  We should use ontrack instead
- createOffer(successCallback, failureCallback[, options]) 
  We should use `aPromise = myPeerConnection.createOffer([options]);` instead
- createAnswer(successCallback, failureCallback[, options]); 
  We should use `aPromise = RTCPeerConnection.createAnswer([options]);` instead

**Comment by dpwspoon** [comment]
We should use https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/ontrack

**Comment by DoruM** [comment]
Hi guys
I am not sure about using ontrack. According to [this table](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/ontrack#Browser_compatibility) Chrome doesn't support ontrack. Furthermore it is experimental technology. Mozilla decided to deprecate the method onaddstream before being implemented in Chrome. If we add it we are probably going to run into problems. Only Firefox supports it actually.

The adapter.js code does seem to add some kind of support for this, but it is a "shim". Do you really think we should use ontrack?

@dpwspoon , @cmebarrow

**Comment by DoruM** [comment]
Changes are done in [this PR](https://github.com/kaazing/webrtc/pull/20). Using ontrack, as per WebRTC API.

**Comment by dpwspoon** [comment]
Thanks @DoruM, as discussed this change brings us to the [latest draft W3C](https://www.w3.org/TR/webrtc/) standard.  The PR looks good to me @cmebarrow can you please confirm since you raised the issue.

**Comment by cmebarrow** [comment]
@DoruM @dpwspoon The changes look fine to me. Do they work in Chrome (given @DoruM 's comment above)? BTW, I wasn't necessarily expecting us to fix this right away, I just filed the ticket to make sure we didn't forget about it. Of course it's good to have it done provided it doesn't break stuff.

**Comment by dpwspoon** [comment]
Thanks, I was getting a funny dom error when things weren't configured correctly.  I thought moving to this API might fix it (or provide a better looking exception) which is why I suggested doing it sooner than later.  @DoruM I believe these work in chrome, please confirm and then lets merge

**Comment by DoruM** [comment]
Actually I am getting errors in chrome. Including the DOM exception.  I will be working on this a bit further.

**Comment by DoruM** [comment]
Issues fixed in [this PR](https://github.com/kaazing/webrtc/pull/22). The code still uses "addStream" method which is obsolete as well. There is no way of getting over it though, since chrome doesn't implement addTrack and adapter.js doesn't do it either.
