### ISSUE TITLE
Clicking "Hangup" breaks the application

### ISSUE THREAD

**Issue by DoruM** [kaazing/webrtc#26]
When clicking "Hang Up", after a call the function "startChat" is called with empty arguments. As such, the app throws the error 

`Uncaught TypeError: registerMessageListenerCallback is not a function`

This is in connection with the changes done for [this PR](https://github.com/kaazing/webrtc/pull/24). 

Please check whether the call to "startChat" is still necessary, and if it is, fix this issue.

**Comment by mgherghe** [comment]
Created [PR](https://github.com/kaazing/webrtc/pull/27).
